name: mbbsfreaks
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"   # ✅ updated for Dart 3.x

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Google Sign-In
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  google_sign_in: ^6.2.1   # ✅ updated, supports Flutter 3.35
  flutter_signin_button: ^2.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.4.2
  firebase_app_check: ^0.4.0+1


  # HTTP for API calls
  http: ^1.1.0
  dio: ^5.4.0
  pdfx: ^2.9.2
  razorpay_flutter: ^1.3.5

  # Google APIs
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0

  # PDF viewing and downloading
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  permission_handler: ^12.0.1

  # Loading and caching
  cached_network_image: ^3.3.1

  # Local storage
  shared_preferences: ^2.2.2

  # Cupertino icons
  cupertino_icons: ^1.0.8
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons.png"

flutter:
  uses-material-design: true

  assets:
    - assets/pyqs.png
    - assets/loggos.jpeg
    - assets/logo.png
    - assets/notes.png
    - assets/question_bank.png
    - assets/quiz.png
